### PR TITLE
Fixes the url

### PR DESCRIPTION
**Pull request by davidpricedev**
This didn't work at all until I fixed the URL by adding the missing "?"

### CODE REVIEW

**Comment by mrbalihai** [comment]
That's not the behaviour I'm seeing on Team City 8.1.2  - what version are you using?

**Comment by davidpricedev** [comment]
I'm using TeamCity 9.0 (build 32060)

**Comment by zlamma** [comment]
Fix to this, and many other improvements are part of the 'most maintained' fork:  

https://github.com/zlamma/tc-radiate

**Comment by zlamma** [comment]
The fork has become the official version now, hence issue is closed.

**Pull request closed without merging**
